# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: Build Web API Project
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration release'

- task: DotNetCoreCLI@2
  displayName: Publish Web API Project
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration release --output $(Build.ArtifactStagingDirectory)/API'
    zipAfterPublish: false
    publishWebProjects: false

- task: CmdLine@2
  displayName: Prepare Azure Function For Publish With API
  inputs:
    script: |
      echo Write your commands here
      mkdir $(Build.ArtifactStagingDirectory)/Final
      cp -r $(Build.ArtifactStagingDirectory)/API/WebAPI $(Build.ArtifactStagingDirectory)/Final
      cp -r $(Build.SourcesDirectory)/HttpTrigger $(Build.ArtifactStagingDirectory)/Final
      cp -r $(Build.SourcesDirectory)/SaveRecord $(Build.ArtifactStagingDirectory)/Final
      cp -r $(Build.SourcesDirectory)/UserTopicProcessor $(Build.ArtifactStagingDirectory)/Final
      cp $(Build.SourcesDirectory)/host.json $(Build.ArtifactStagingDirectory)/Final/host.json      
      cd $(Build.ArtifactStagingDirectory)/Final      
      echo Hello world
      tree

- task: ArchiveFiles@1
  inputs:
    includeRootFolder: false
    archiveType: default
    rootFolder: $(Build.ArtifactStagingDirectory)/Final
    archiveFile: $(Build.ArtifactStagingDirectory)/Final.zip
  
- task: PublishBuildArtifacts@1
  inputs:
     ArtifactName: drop
     PathtoPublish: $(Build.ArtifactStagingDirectory)/Final     

